teco/dproj/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^dproj/', include('dproj.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
)

teco/dproj/piel/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.

from django.db import models

class Magnitud(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    nombre = models.CharField(max_length=120, blank=True)
    minimo = models.DecimalField(null=True, max_digits=13, decimal_places=1, blank=True)
    maximo = models.DecimalField(null=True, max_digits=13, decimal_places=1, blank=True)
    unidad = models.CharField(max_length=60, blank=True)
    uni = models.CharField(max_length=15, blank=True)
    class Meta:
        db_table = u'magnitudes'

    def __unicode__(self):
        return u"%s en %s" % (self.nombre, self.uni)
        
class Medida(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    texto = models.CharField(max_length=240, blank=True)

    class Meta:
        db_table = u'medidas'

    def __unicode__(self):
        return self.texto
        
class Provincia(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    zona_id = models.IntegerField(null=True, blank=True)
    nombre = models.CharField(max_length=150, blank=True)
    class Meta:
        db_table = u'provincias'


class Sitio(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    nombre = models.CharField(max_length=120, blank=True)
    ccc = models.CharField(max_length=9, blank=True)
    port = models.IntegerField(unique=True)
    online = models.IntegerField() #0: online 1: error
    class Meta:
        db_table = u'sitios'

    def __unicode__(self):
        return self.ccc

class RobotTipoIO(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    nombre = models.CharField(max_length=60, blank=True)
    campo = models.CharField(max_length=10, blank=True) # campo de la tabla Valores
    
    class Meta:
        db_table = u'robots_tipoio'

    def esEA(self):
        return self.nombre.startswith('Entrada Analogica')
        
    def esRE(self):
        return self.nombre.startswith('Registro')

    def esSD(self):
        return self.nombre.startswith('Salida Digital')

    def esED(self):
        return self.nombre.startswith('Entrada Digital')
        
    def __unicode__(self):
        return self.nombre
        
class RobotTipo(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    nombre = models.CharField(max_length=120, blank=True)
    mascara = models.CharField(max_length=500, blank=True)
        
    class Meta:
        db_table = u'robots_tipos'
        
    def __unicode__(self):
        return self.nombre
                
class Robot(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    tipo = models.ForeignKey(RobotTipo, null=True, db_column='tipo', blank=True)
    nombre = models.CharField(max_length=120)
    mbdir = models.CharField(max_length=6, blank=True)
    observaciones = models.TextField(blank=True)
    sitio = models.ForeignKey(Sitio, null=True, db_column='sitio', blank=True)
    last_valor = models.ForeignKey('Valor', null=True, blank=True, db_column='last_valor', related_name='Valor.robot')
    online = models.IntegerField() #0: online 1: error
    
    class Meta:
        db_table = u'robots'

    def __unicode__(self):
        return u"%s en %s" % (self.mbdir, self.sitio)

    def config_dict(self, gcond=None):

        configuracion = self.robotconfig_set.all()
        if gcond is not None:
            configuracion = configuracion.filter(graficable=gcond)
        entradasanalogicas = [c for c in configuracion if c.tipoio.esEA()]
        registros = [c for c in configuracion if c.tipoio.esRE()]
        salidasdigitales = [c for c in configuracion if c.tipoio.esSD()]
        entradasdigitales = [c for c in configuracion if c.tipoio.esED()]
        return {'entradasanalogicas': entradasanalogicas,
                'registros': registros,
                'salidasdigitales': salidasdigitales,
                'entradasdigitales': entradasdigitales
               }

    def confignames_dict(self, gcond=None):
    
        configuracion = self.robotconfig_set.all()
        if gcond is not None:
            configuracion = configuracion.filter(graficable=gcond)
        entradasanalogicas = [c.tipoio.campo for c in configuracion if c.tipoio.esEA()]
        registros = [c.tipoio.campo for c in configuracion if c.tipoio.esRE()]
        salidasdigitales = [c.tipoio.campo for c in configuracion if c.tipoio.esSD()]
        entradasdigitales = [c.tipoio.campo for c in configuracion if c.tipoio.esED()]
        return {u'entradasanalogicas': entradasanalogicas,
                u'registros': registros,
                u'salidasdigitales': salidasdigitales,
                u'entradasdigitales': entradasdigitales
               }
               
class RobotConfig(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    robot = models.ForeignKey(Robot, db_column='robot')
    tipoio = models.ForeignKey(RobotTipoIO, null=True, db_column='tipoio', blank=True)   
    magnitud = models.ForeignKey(Magnitud, null=True, db_column='magnitud', blank=True)
    medida = models.ForeignKey(Medida, null=True, db_column='medida', blank=True)
    editable = models.BooleanField()
    graficable = models.BooleanField() 
    
    class Meta:
        db_table = u'robots_config'

class Valor(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    robot = models.ForeignKey(Robot, null=True, db_column='robot', blank=True)
    ea1 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    ea2 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    ea3 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    ea4 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    ea5 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    ea6 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    ea7 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    ea8 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    ea9 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    ea10 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    re1 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    re2 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    re3 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    re4 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    re5 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    re6 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    re7 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    re8 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    re9 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    re10 = models.DecimalField(null=True, max_digits=5, decimal_places=2, blank=True)
    sd1 = models.IntegerField(null=True, blank=True)
    sd2 = models.IntegerField(null=True, blank=True)
    sd3 = models.IntegerField(null=True, blank=True)
    sd4 = models.IntegerField(null=True, blank=True)
    sd5 = models.IntegerField(null=True, blank=True)
    sd6 = models.IntegerField(null=True, blank=True)
    sd7 = models.IntegerField(null=True, blank=True)
    sd8 = models.IntegerField(null=True, blank=True)
    sd9 = models.IntegerField(null=True, blank=True)
    sd10 = models.IntegerField(null=True, blank=True)
    ed1 = models.IntegerField(null=True, blank=True)
    ed2 = models.IntegerField(null=True, blank=True)
    ed3 = models.IntegerField(null=True, blank=True)
    ed4 = models.IntegerField(null=True, blank=True)
    ed5 = models.IntegerField(null=True, blank=True)
    ed6 = models.IntegerField(null=True, blank=True)
    ed7 = models.IntegerField(null=True, blank=True)
    ed8 = models.IntegerField(null=True, blank=True)
    ed9 = models.IntegerField(null=True, blank=True)
    ed10 = models.IntegerField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True)
    class Meta:
        db_table = u'valores'
        ordering = ('id',)

EVENTO_CHOICES = (
    ('I', 'Informacion'),
    ('W', 'Advertencia'),
    ('A', 'Alerta'),
)

class Evento(models.Model):
    timestamp = models.DateTimeField(null=True, auto_now=True)
    tipo = models.CharField(max_length=1, choices=EVENTO_CHOICES)
    texto = models.CharField(max_length=60, blank=True)
    
    def __unicode__(self):
        return "%s: %s - %s" % (self.timestamp, self.tipo, self.texto)

# Signals

from django.db.models.signals import post_save

def record_last_valor(sender, instance, created, **kwargs):
    print "LAST_VALOR"*5
    print instance, created
    if created:
        instance.robot.last_valor = instance
        instance.robot.save()
        print instance.robot.last_valor
        print instance == instance.robot.last_valor

post_save.connect(record_last_valor, sender=Valor)

teco/dproj/templates/celu.html
<html>
<head title="{{ title }}">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
</head>
<body>
<h1>{{ sitios|length }} sitio{{ sitios|pluralize }}</h1>
    <div>
    {% for s in sitios %}
    <h2><a href="/celu/{{ s.ccc }}">{{ s.nombre }}</a></h2>
    {% endfor %}
    </div>

</body>
</html>

teco/dproj/templates/graph.html
<div xmlns:nevow="http://nevow.com/ns/nevow/0.1"
    xmlns:athena="http://divmod.org/ns/athena/0.7"
    nevow:render="liveElement">
    <h2>Grafica: {{ robot.nombre }} en <a href="/sitios/{{ robot.sitio }}/">{{ robot.sitio }}</a></h2>
    <p name="choices">Mostrar:{% for c in analogicas %}
                              <input type="checkbox" name="{{ c.tipoio.campo }}" 
                              checked="checked">
                              <span title="{{ c.medida.texto}} en {{ c.magnitud.uni }}">{{ c.tipoio.campo }}</span>
                              </input>
                              {% endfor %}                            
    </p>
    <div name="placeholder" style="width:900px;height:250px"></div>
    <p id="hoverdata">
    Mouse hovers at (
    <span name="x">0.0</span>
    ,
    <span name="y">0.0</span>
    ).
    <span name="clickdata"></span>
    </p>
    <p><input name="enableTooltip" type="checkbox"/>Enable tooltip</p>

    <p name="choices2">Mostrar:{% for c in digitales %}
                              <input type="checkbox" name="{{ c.tipoio.campo }}" 
                              checked="checked">
                              <span title="{{ c.medida.texto}}">{{ c.tipoio.campo }}</span>
                              </input>
                              {% endfor %}                            
    </p>
    <div name="placeholder2" style="width:900px;height:400px"></div>
    <form name="graphElement">
        <athena:handler event="onsubmit" handler="doStart" />
        <input name="botonGraficar" type="submit" value="Graficar" />
    </form>
</div>    

teco/dproj/templates/my_template.html
y dice baaaaaaaaaarrr {{ foo }}.

teco/dproj/templates/robot.html
<html>
<head title="{{ robot.nombre }} en {{ sitio.nombre }}">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
</head>
<body>
<h1>{{ robot.nombre }} en {{ sitio.nombre }}</h1>
<p>{{ robot.observaciones|default_if_none:"" }}</p>
<ul>
<li><a href="control/">Control Remoto</a></li>
<li><a href="grafica/">Gr&aacute;fica en tiempo real</a></li>
</ul>

<h2>Configuraci&oacute;n del robot</h2>
<h3>Entradas Analógicas</h3>
{% for c in robot.config_dict.entradasanalogicas %}
<span>{{ c.medida.texto }} ({{ c.tipoio.campo }})</span>{% if c.magnitud.uni %} en {{ c.magnitud.uni }}{% endif %}<br/>
{% endfor %}
<h3>Registros</h3>
{% for c in robot.config_dict.registros %}
<span>{{ c.medida.texto }} ({{ c.tipoio.campo }})</span>{% if c.magnitud.uni %} en {{ c.magnitud.uni }}{% endif %}<br/>
{% endfor %}
<h3>Entradas Digitales</h3>
{% for c in robot.config_dict.entradasdigitales %}
<span>{{ c.medida.texto }} ({{ c.tipoio.campo }})</span>{% if c.magnitud.uni %} en {{ c.magnitud.uni }}{% endif %}<br/>
{% endfor %}
<h3>Salidas Digitales</h3>
{% for c in robot.config_dict.salidasdigitales %}
<span>{{ c.medida.texto }} ({{ c.tipoio.campo }})</span>{% if c.magnitud.uni %} en {{ c.magnitud.uni }}{% endif %}<br/>
{% endfor %}
<h2>&Uacute;ltimos valores recibidos</h2>
<table border="1">
<tr><th>ea1</th><th>ea2</th><th>ea3</th><th>ea4</th><th>re1</th><th>re2</th><th>re3</th><th>re4</th>
<th>sd1</th><th>sd2</th><th>sd3</th><th>sd4</th><th>ed1</th><th>ed2</th><th>timestamp</th></tr>
{% for v in valores %}
<tr>
<td>{{ v.ea1 }}</td><td>{{ v.ea2 }}</td><td>{{ v.ea3 }}</td><td>{{ v.ea4 }}</td>
<td>{{ v.re1 }}</td><td>{{ v.re2 }}</td><td>{{ v.re3 }}</td><td>{{ v.re4 }}</td>
<td>{{ v.sd1 }}</td><td>{{ v.sd2 }}</td><td>{{ v.sd3 }}</td><td>{{ v.sd4 }}</td>
<td>{{ v.ed1 }}</td><td>{{ v.ed2 }}</td><td>{{ v.timestamp }}</td>
</tr>
{% endfor %}
</table>
</body>
</html>

teco/dproj/templates/sitio.html
<html>
<head title="{{ sitio.nombre }}">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
</head>
<body>
<h1>{{ sitio.nombre }}</h1>
    <div>
        {% for r in sitio.robot_set.all %}
        <a href="/sitios/{{ sitio.ccc }}/{{ r.mbdir }}/"><h2>{{ r.nombre }}</h2></a> 
        {% endfor %}
    </div>

</body>
</html>

teco/dproj/templates/sitiocelu.html
<html>
<head title="{{ sitio.nombre }}">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
</head>
<body>
<h1>{{ sitio.ccc }} - {{ valores.0.timestamp|date:"d/m/y H:i" }} </h1>
    <div>
            R: {{ valores.1.ea1 }} Vca <br/>
            S: {{ valores.1.ea2 }} Vca <br/>
            T: {{ valores.1.ea3 }} Vca <br/>
            Vbat: {{ valores.2.ea5 }} Vcc <br/>
            Temp: {{ valores.0.ea4 }} C <br/>
    </div>

</body>
</html>

teco/dproj/templates/sitios.html
<html>
<head title="{{ title }}">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
</head>
<body>
<h1>{{ clientes|length }} cliente{{ clientes|pluralize }} conectado{{ clientes|pluralize }}</h1>
    <div>
    {% for c in clientes %}
    <h2> {{ c.sitio.nombre }}:  </h2>
        {% for r in c.sitio.robot_set.all %}
        <a href="/sitios/{{ c.sitio.ccc }}/{{ r.mbdir }}/">{{ r.nombre }}</a><br/> 
        {% endfor %}
    {% endfor %}
    </div>

</body>
</html>

teco/dproj/templates/tero.html
<div xmlns:nevow="http://nevow.com/ns/nevow/0.1"
    xmlns:athena="http://divmod.org/ns/athena/0.7"
    nevow:render="liveElement">
    
    <h2>Control Remoto: {{ robot.nombre }} en <a href="/sitios/{{ robot.sitio }}/">{{ robot.sitio }}</a></h2>
    <form name="terElement">
        <athena:handler event="onsubmit" handler="doRead" />
        <input name="botonLeer" type="submit" value="Leer" />
        <img name="reading_img" align="middle" src="/imgs/ajax-loader.gif" alt="loading" style="display: none"/>    
    </form>
    
<table style="width:100%">
  <tbody>
    <tr>
      <td style="width:50%; vertical-align: top">
      
        <div name="entradas-analogicas">
        <h3>Entradas Analógicas</h3>
        {% for ea in entradasanalogicas %}
        <span>{{ ea.medida.texto }}:</span><span style="color:#339900; font-weight: bold" name="{{ ea.tipoio.campo }}"></span> {{ ea.magnitud.uni }}<br/>
        {% endfor %}
        </div>
      
      </td>
      <td style="width:50%; vertical-align: top">
      
        <div name="registros">
        <h3>Registros</h3>
        <form name="terElementChange">
            <athena:handler event="onsubmit" handler="doChange" />
        {% for re in registros %}
        <span>
        <input type="radio" name="consignas" value="{{ forloop.counter }}"
        {% if forloop.first %}checked="checked"{% endif %} {% if not re.editable %}disabled="disabled"{% endif %}/> {# problemas si el primero no es editable #} 
        {{ re.medida.texto }}:</span><span style="color:#339900; font-weight: bold" name="{{ re.tipoio.campo }}"></span> {{ re.magnitud.uni }}<br/>
        {% endfor %}
        <div align="right">
        <img  class="changing" name="changing_img" align="middle" src="/imgs/ajax-loader-ball.gif" alt="loading" style="display: none"/>    
        <input type="text" name="valor_consigna" size="2" disabled="disabled"/>
        <input name="botonCambiar" type="submit" value="Cambiar" disabled="disabled"/>
        <span name="error_msg"></span>
        </div>
        </form>                
        </div>      
         
      </td>
    </tr>
    <tr>
      <td style="width:50%; vertical-align: top">

        <div name="entradasdigitales">
        <h3>Entradas Digitales</h3>
        {% for ed in entradasdigitales %}
        <span>{{ ed.medida.texto }}:</span><span style="color:#339900; font-weight: bold" name="{{ ed.tipoio.campo }}"></span> {{ ed.magnitud.uni }}<br/>
        {% endfor %}
        </div>          
      
      </td>
      <td style="width:50%; vertical-align: top">

        <div name="salidasdigitales">
        <h3>Salidas Digitales</h3>
        <form name="sdChange">
        <athena:handler event="onsubmit" handler="doChangeSD" />
        {% for sd in salidasdigitales %}
        <input type="radio" name="consignasSD" value="{{ forloop.counter }}"
        {% if forloop.first %}checked="checked"{% endif %} {% if not sd.editable %}disabled="disabled"{% endif %}/> {# problemas si el primero no es editable #} 
        <span>{{ sd.medida.texto }}:</span><span style="color:#339900; font-weight: bold" name="{{ sd.tipoio.campo }}"></span> {{ sd.magnitud.uni }}
        <br/>
        {% endfor %}
        <div align="right">
        <img class="changing" name="changing_imgSD" align="middle" src="/imgs/ajax-loader-ball.gif" alt="loading" style="display: none"/>    
        <input name="botonCambiar" type="submit" value="Cambiar" disabled="disabled"/>
        <span name="error_msg"></span>
        </div>

        </form>
        </div>
              
      </td>
    </tr>
  </tbody>
</table>


</div>